[package]
name = "ava-finance-alerts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
postgres = "0.17.2"
serde =  { version = "1.0.158", features = ["derive"] }
chrono = "0.4.19"